spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=kunal123
kafka.bootstrapAddress=localhost:9092
spot.topic.name=spot-price
vol.topic.name=vol
vanilla.option.topic.name=vol
spot.topic.parititioncount=3
vol.topic.partitioncount=3
vanillaoption.topic.partitioncount=3

